name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: aman879/docker-react
      - name: Build the Docker image
        run: docker build -t aman879/dreact -f Dockerfile.dev .
      - name: Run the docker container
        run: docker run -e CI=true aman879/dreact npm run test
