name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-test-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: aman879/docker-react
    - name: Build the Docker image
      run: docker build -t aman879/docker-react -f Dockerfile.dev
