name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t react-app -f Dockerfile.dev .
      - name: Test the Docker container
        run: docker run -e CI=true react-app npm run test
